# Information Retrieval


Assignment 3

Team members:

1: Tooraj *Taraz*

2: MohammadReza Tashakkori

3: Iman Jalali

4: Seyed MohammadTaha Tabatabayi

In [1]:
import hazm
import nltk
import pandas

In [2]:
df_persian = pandas.read_excel('/home/toorajtaraz/Documents/projects/ClassProjects/final_books.xlsx')
df_persian.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2824 entries, 0 to 2823
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     2824 non-null   object
 1   date      2824 non-null   object
 2   content   2441 non-null   object
 3   category  2824 non-null   object
 4   author    2824 non-null   object
 5   comments  2824 non-null   object
dtypes: object(6)
memory usage: 132.5+ KB

In [3]:
df_persian.head()

,title,date,content,category,author,comments
0,بهترین درسهای زندگی‎,۲ دی ۱۳۹۸,تی دی جیکس یک کشیش، نویسنده، سخنران آمریکایی ...,روانشناسی,سارا رزولت,بدون دیدگاه
1,از سلاجقه تا صفویه,۱ دی ۱۳۹۸,کتاب حاضر که اینک در دسترس خوانندگان محترم قر...,تاریخ ایران,نصرت الله مشکوتی,بدون دیدگاه
2,سرگذشت رضاشاه,۲۹ آذر ۱۳۹۸,دکتر فتح الله بینا تحصیلات خود را در رشته پزش...,تاریخ ایران,فتح الله بینا,بدون دیدگاه
3,سیری نوین در فرگشت و اسرار مغز,۲۸ آذر ۱۳۹۸,مجموعه پیش رو مطالبیست که در گروه Evolution ت...,علم و دانش,مانی منوچهری,بدون دیدگاه
4,آسمان پرستاره,۲۶ آذر ۱۳۹۸,کتاب آسمان پرستاره نوشته‌ی کتی هایدن، به زبان...,کودکان و نوجوانان,کتی هایدن,بدون دیدگاه

In [4]:
from __future__ import unicode_literals
from hazm import Normalizer

In [5]:
normalizer = Normalizer()

In [6]:
import numpy as np

In [7]:
normalized_persian_tokens = []
all_punct = '''،!()-[]{};:'"\,<>./؟?@#$%^&*_~'''
for index, row in df_persian.iterrows():
  content = row["content"]
  try:
    if len(content) < 1:
      continue
  except:
    continue
  for p in all_punct:
    content = content.replace(p, '')
  normalized_content = normalizer.normalize(content)
  normalized_persian_tokens.append((index, normalized_content))



normalized_persian_tokens[0]

(0,
 ' تی دی جیکس یک کشیش نویسنده سخنران آمریکایی است سمینار\u200cهای تی دی جیکس اغلب انگیزشی و مذهبی است به همین دلیل او در ایران به سخنران انگیزشی سیاه پوست لقب گرفته است در زندگینامه تی دی جیکس شاهد فعالیت\u200cهای مختلفی هستیم که هر کدام از آنها خواهان تجربه و تلاش زیادی هستند مواردی که اعلام شد تنها بخشی از فعالیت\u200cهای جیکس است او هم اکنون کشیش خانه پاتر است و مخاطبان بسیاری دارد موعظه\u200cهای و سخنرانی\u200cها تی دی جیکس در کلیسا از شبکه\u200cهای تلویزیونی و رادیویی مختلف پخش می\u200cشوند این کتاب گزیده\u200cای از سخنرانی\u200cهای آقای جیکز یکی از بهترین سخنران\u200cهای انگیزشی در دنیا است امید است با مطالعه دقیق و باور عمیق تغییری مثبت در زندگیتان ایجاد شود')

In [8]:
from hazm import sent_tokenize, word_tokenize

In [9]:
tokenized_normal_sent_persian = []
for index, normalized_sent in normalized_persian_tokens:
  sent_tokens = sent_tokenize(normalized_sent)
  word_tokens = word_tokenize(normalized_sent)
  tokenized_normal_sent_persian.append((index, sent_tokens, word_tokens))

persian_final_df = pandas.DataFrame(tokenized_normal_sent_persian, columns =['index in original persian df', 'sent_token', 'word_token'])
persian_final_df.head()

# persian_final_df.to_csv("persian_token.csv")

,index in original persian df,sent_token,word_token
0,0,[تی دی جیکس یک کشیش نویسنده سخنران آمریکایی اس...,"[تی, دی, جیکس, یک, کشیش, نویسنده, سخنران, آمری..."
1,1,[کتاب حاضر که اینک در دسترس خوانندگان محترم قر...,"[کتاب, حاضر, که, اینک, در, دسترس, خوانندگان, م..."
2,2,[دکتر فتح الله بینا تحصیلات خود را در رشته پزش...,"[دکتر, فتح, الله, بینا, تحصیلات, خود, را, در, ..."
3,3,[مجموعه پیش رو مطالبیست که در گروه Evolution ت...,"[مجموعه, پیش, رو, مطالبیست, که, در, گروه, Evol..."
4,4,[کتاب آسمان پرستاره نوشته‌ی کتی هایدن به زبانی...,"[کتاب, آسمان, پرستاره, نوشته‌ی, کتی, هایدن, به..."

In [10]:
# adding sent and word tokens as coloums to the original df based on index
df_persian['sent_token'] = persian_final_df['sent_token']
df_persian['word_token'] = persian_final_df['word_token']

df_persian.head()

,title,date,content,category,author,comments,sent_token,word_token
0,بهترین درسهای زندگی‎,۲ دی ۱۳۹۸,تی دی جیکس یک کشیش، نویسنده، سخنران آمریکایی ...,روانشناسی,سارا رزولت,بدون دیدگاه,[تی دی جیکس یک کشیش نویسنده سخنران آمریکایی اس...,"[تی, دی, جیکس, یک, کشیش, نویسنده, سخنران, آمری..."
1,از سلاجقه تا صفویه,۱ دی ۱۳۹۸,کتاب حاضر که اینک در دسترس خوانندگان محترم قر...,تاریخ ایران,نصرت الله مشکوتی,بدون دیدگاه,[کتاب حاضر که اینک در دسترس خوانندگان محترم قر...,"[کتاب, حاضر, که, اینک, در, دسترس, خوانندگان, م..."
2,سرگذشت رضاشاه,۲۹ آذر ۱۳۹۸,دکتر فتح الله بینا تحصیلات خود را در رشته پزش...,تاریخ ایران,فتح الله بینا,بدون دیدگاه,[دکتر فتح الله بینا تحصیلات خود را در رشته پزش...,"[دکتر, فتح, الله, بینا, تحصیلات, خود, را, در, ..."
3,سیری نوین در فرگشت و اسرار مغز,۲۸ آذر ۱۳۹۸,مجموعه پیش رو مطالبیست که در گروه Evolution ت...,علم و دانش,مانی منوچهری,بدون دیدگاه,[مجموعه پیش رو مطالبیست که در گروه Evolution ت...,"[مجموعه, پیش, رو, مطالبیست, که, در, گروه, Evol..."
4,آسمان پرستاره,۲۶ آذر ۱۳۹۸,کتاب آسمان پرستاره نوشته‌ی کتی هایدن، به زبان...,کودکان و نوجوانان,کتی هایدن,بدون دیدگاه,[کتاب آسمان پرستاره نوشته‌ی کتی هایدن به زبانی...,"[کتاب, آسمان, پرستاره, نوشته‌ی, کتی, هایدن, به..."

In [11]:
# first we need to remove stop words from the persian text using hazm
from hazm import stopwords_list

stopwords = stopwords_list()

# removing stop words from the persian text and storing the cleaned word tokens in a new column
def remove_stopwords(word_tokens):
  # if word_tokens is not a list, then return an empty list
    if not isinstance(word_tokens, list):
        return []
    # if word_tokens is a list, then return a list of words that are not in the stopwords list
    return [word for word in word_tokens if word not in stopwords]

df_persian['hazm_cleaned_word_token'] = df_persian['word_token'].apply(remove_stopwords)

df_persian.head()

,title,date,content,category,author,comments,sent_token,word_token,hazm_cleaned_word_token
0,بهترین درسهای زندگی‎,۲ دی ۱۳۹۸,تی دی جیکس یک کشیش، نویسنده، سخنران آمریکایی ...,روانشناسی,سارا رزولت,بدون دیدگاه,[تی دی جیکس یک کشیش نویسنده سخنران آمریکایی اس...,"[تی, دی, جیکس, یک, کشیش, نویسنده, سخنران, آمری...","[تی, دی, جیکس, کشیش, نویسنده, سخنران, آمریکایی..."
1,از سلاجقه تا صفویه,۱ دی ۱۳۹۸,کتاب حاضر که اینک در دسترس خوانندگان محترم قر...,تاریخ ایران,نصرت الله مشکوتی,بدون دیدگاه,[کتاب حاضر که اینک در دسترس خوانندگان محترم قر...,"[کتاب, حاضر, که, اینک, در, دسترس, خوانندگان, م...","[کتاب, حاضر, اینک, دسترس, خوانندگان, محترم, قر..."
2,سرگذشت رضاشاه,۲۹ آذر ۱۳۹۸,دکتر فتح الله بینا تحصیلات خود را در رشته پزش...,تاریخ ایران,فتح الله بینا,بدون دیدگاه,[دکتر فتح الله بینا تحصیلات خود را در رشته پزش...,"[دکتر, فتح, الله, بینا, تحصیلات, خود, را, در, ...","[دکتر, فتح, الله, بینا, تحصیلات, رشته, پزشکی, ..."
3,سیری نوین در فرگشت و اسرار مغز,۲۸ آذر ۱۳۹۸,مجموعه پیش رو مطالبیست که در گروه Evolution ت...,علم و دانش,مانی منوچهری,بدون دیدگاه,[مجموعه پیش رو مطالبیست که در گروه Evolution ت...,"[مجموعه, پیش, رو, مطالبیست, که, در, گروه, Evol...","[مجموعه, مطالبیست, گروه, Evolution, توسط, اینج..."
4,آسمان پرستاره,۲۶ آذر ۱۳۹۸,کتاب آسمان پرستاره نوشته‌ی کتی هایدن، به زبان...,کودکان و نوجوانان,کتی هایدن,بدون دیدگاه,[کتاب آسمان پرستاره نوشته‌ی کتی هایدن به زبانی...,"[کتاب, آسمان, پرستاره, نوشته‌ی, کتی, هایدن, به...","[کتاب, آسمان, پرستاره, نوشته‌ی, کتی, هایدن, زب..."

In [12]:
# we are going to do stemming and lemmentization on the persian text using hazm and parsivar
# first we handle things using hazm
# we are going to use the stemmer and lemmatizer from hazm

from hazm import Stemmer, Lemmatizer

In [13]:
# we stem the word_tokens in the persian df using hazm stemmer
stemmer = Stemmer()
hazm_stemmed_persian_tokens = []

for index, row in df_persian.iterrows():
    word_tokens = row["hazm_cleaned_word_token"]
    stemmed_word_tokens = []
    # if word_tokens is not a list we skip it
    if not isinstance(word_tokens, list):
        hazm_stemmed_persian_tokens.append((index, stemmed_word_tokens))
        continue
    for word in word_tokens:
        # if word is not a str we skip it
        if not isinstance(word, str):
            continue
        stemmed_word = stemmer.stem(word)
        stemmed_word_tokens.append(stemmed_word)
    hazm_stemmed_persian_tokens.append((index, stemmed_word_tokens))

# add a new column to the persian df for the stemmed tokens
df_persian['hazm_stemmed_word_token'] = [x[1] for x in hazm_stemmed_persian_tokens]

df_persian.head()

,title,date,content,category,author,comments,sent_token,word_token,hazm_cleaned_word_token,hazm_stemmed_word_token
0,بهترین درسهای زندگی‎,۲ دی ۱۳۹۸,تی دی جیکس یک کشیش، نویسنده، سخنران آمریکایی ...,روانشناسی,سارا رزولت,بدون دیدگاه,[تی دی جیکس یک کشیش نویسنده سخنران آمریکایی اس...,"[تی, دی, جیکس, یک, کشیش, نویسنده, سخنران, آمری...","[تی, دی, جیکس, کشیش, نویسنده, سخنران, آمریکایی...","[ت, د, جیکس, کش, نویسنده, سخنر, آمریکا, سمینار..."
1,از سلاجقه تا صفویه,۱ دی ۱۳۹۸,کتاب حاضر که اینک در دسترس خوانندگان محترم قر...,تاریخ ایران,نصرت الله مشکوتی,بدون دیدگاه,[کتاب حاضر که اینک در دسترس خوانندگان محترم قر...,"[کتاب, حاضر, که, اینک, در, دسترس, خوانندگان, م...","[کتاب, حاضر, اینک, دسترس, خوانندگان, محترم, قر...","[کتاب, حاضر, اینک, دسترس, خوانندگ, محتر, قرار,..."
2,سرگذشت رضاشاه,۲۹ آذر ۱۳۹۸,دکتر فتح الله بینا تحصیلات خود را در رشته پزش...,تاریخ ایران,فتح الله بینا,بدون دیدگاه,[دکتر فتح الله بینا تحصیلات خود را در رشته پزش...,"[دکتر, فتح, الله, بینا, تحصیلات, خود, را, در, ...","[دکتر, فتح, الله, بینا, تحصیلات, رشته, پزشکی, ...","[دک, فتح, الله, بینا, تحصیل, رشته, پزشک, دنبال..."
3,سیری نوین در فرگشت و اسرار مغز,۲۸ آذر ۱۳۹۸,مجموعه پیش رو مطالبیست که در گروه Evolution ت...,علم و دانش,مانی منوچهری,بدون دیدگاه,[مجموعه پیش رو مطالبیست که در گروه Evolution ت...,"[مجموعه, پیش, رو, مطالبیست, که, در, گروه, Evol...","[مجموعه, مطالبیست, گروه, Evolution, توسط, اینج...","[مجموعه, مطالبیس, گروه, Evolution, توسط, اینجا..."
4,آسمان پرستاره,۲۶ آذر ۱۳۹۸,کتاب آسمان پرستاره نوشته‌ی کتی هایدن، به زبان...,کودکان و نوجوانان,کتی هایدن,بدون دیدگاه,[کتاب آسمان پرستاره نوشته‌ی کتی هایدن به زبانی...,"[کتاب, آسمان, پرستاره, نوشته‌ی, کتی, هایدن, به...","[کتاب, آسمان, پرستاره, نوشته‌ی, کتی, هایدن, زب...","[کتاب, آس, پرستاره, نوشته, کت, هایدن, زبان, سا..."

In [14]:
# only view the first 5 rows of the persian df and word_token and hazm_stemmed_word_token columns
df_persian[['hazm_cleaned_word_token', 'hazm_stemmed_word_token']].head()

,hazm_cleaned_word_token,hazm_stemmed_word_token
0,"[تی, دی, جیکس, کشیش, نویسنده, سخنران, آمریکایی...","[ت, د, جیکس, کش, نویسنده, سخنر, آمریکا, سمینار..."
1,"[کتاب, حاضر, اینک, دسترس, خوانندگان, محترم, قر...","[کتاب, حاضر, اینک, دسترس, خوانندگ, محتر, قرار,..."
2,"[دکتر, فتح, الله, بینا, تحصیلات, رشته, پزشکی, ...","[دک, فتح, الله, بینا, تحصیل, رشته, پزشک, دنبال..."
3,"[مجموعه, مطالبیست, گروه, Evolution, توسط, اینج...","[مجموعه, مطالبیس, گروه, Evolution, توسط, اینجا..."
4,"[کتاب, آسمان, پرستاره, نوشته‌ی, کتی, هایدن, زب...","[کتاب, آس, پرستاره, نوشته, کت, هایدن, زبان, سا..."

In [15]:
# now we handle lemmentization using hazm lemmatizer
lemmatizer = Lemmatizer()
hazm_lemmatized_persian_tokens = []

for index, row in df_persian.iterrows():
    word_tokens = row["hazm_cleaned_word_token"]
    lemmatized_word_tokens = []
    # if word_tokens is not a list we skip it
    if not isinstance(word_tokens, list):
        hazm_lemmatized_persian_tokens.append((index, lemmatized_word_tokens))
        continue
    for word in word_tokens:
        # if word is not a str we skip it
        if not isinstance(word, str):
            continue
        lemmatized_word = lemmatizer.lemmatize(word)
        lemmatized_word_tokens.append(lemmatized_word)
    hazm_lemmatized_persian_tokens.append((index, lemmatized_word_tokens))

# add a new column to the persian df for the lemmatized tokens
df_persian['hazm_lemmatized_word_token'] = [x[1] for x in hazm_lemmatized_persian_tokens]

df_persian.head()

,title,date,content,category,author,comments,sent_token,word_token,hazm_cleaned_word_token,hazm_stemmed_word_token,hazm_lemmatized_word_token
0,بهترین درسهای زندگی‎,۲ دی ۱۳۹۸,تی دی جیکس یک کشیش، نویسنده، سخنران آمریکایی ...,روانشناسی,سارا رزولت,بدون دیدگاه,[تی دی جیکس یک کشیش نویسنده سخنران آمریکایی اس...,"[تی, دی, جیکس, یک, کشیش, نویسنده, سخنران, آمری...","[تی, دی, جیکس, کشیش, نویسنده, سخنران, آمریکایی...","[ت, د, جیکس, کش, نویسنده, سخنر, آمریکا, سمینار...","[تی, دی, جیکس, کشیش, نویسنده, سخنران, آمریکایی..."
1,از سلاجقه تا صفویه,۱ دی ۱۳۹۸,کتاب حاضر که اینک در دسترس خوانندگان محترم قر...,تاریخ ایران,نصرت الله مشکوتی,بدون دیدگاه,[کتاب حاضر که اینک در دسترس خوانندگان محترم قر...,"[کتاب, حاضر, که, اینک, در, دسترس, خوانندگان, م...","[کتاب, حاضر, اینک, دسترس, خوانندگان, محترم, قر...","[کتاب, حاضر, اینک, دسترس, خوانندگ, محتر, قرار,...","[کتاب, حاضر, اینک, دسترس, خوانندگان, محترم, قر..."
2,سرگذشت رضاشاه,۲۹ آذر ۱۳۹۸,دکتر فتح الله بینا تحصیلات خود را در رشته پزش...,تاریخ ایران,فتح الله بینا,بدون دیدگاه,[دکتر فتح الله بینا تحصیلات خود را در رشته پزش...,"[دکتر, فتح, الله, بینا, تحصیلات, خود, را, در, ...","[دکتر, فتح, الله, بینا, تحصیلات, رشته, پزشکی, ...","[دک, فتح, الله, بینا, تحصیل, رشته, پزشک, دنبال...","[دکتر, فتح, الله, بینا, تحصیلات, رشته, پزشک, د..."
3,سیری نوین در فرگشت و اسرار مغز,۲۸ آذر ۱۳۹۸,مجموعه پیش رو مطالبیست که در گروه Evolution ت...,علم و دانش,مانی منوچهری,بدون دیدگاه,[مجموعه پیش رو مطالبیست که در گروه Evolution ت...,"[مجموعه, پیش, رو, مطالبیست, که, در, گروه, Evol...","[مجموعه, مطالبیست, گروه, Evolution, توسط, اینج...","[مجموعه, مطالبیس, گروه, Evolution, توسط, اینجا...","[مجموعه, مطالبیست, گروه, Evolution, توسط, اینج..."
4,آسمان پرستاره,۲۶ آذر ۱۳۹۸,کتاب آسمان پرستاره نوشته‌ی کتی هایدن، به زبان...,کودکان و نوجوانان,کتی هایدن,بدون دیدگاه,[کتاب آسمان پرستاره نوشته‌ی کتی هایدن به زبانی...,"[کتاب, آسمان, پرستاره, نوشته‌ی, کتی, هایدن, به...","[کتاب, آسمان, پرستاره, نوشته‌ی, کتی, هایدن, زب...","[کتاب, آس, پرستاره, نوشته, کت, هایدن, زبان, سا...","[کتاب, آسمان, پرستاره, نوشته, کت, هایدن, زبان,..."

In [16]:
# only view the first 5 rows of the persian df and word_token and hazm_lemmatized_word_token columns
df_persian[['hazm_cleaned_word_token', 'hazm_lemmatized_word_token']].head()

,hazm_cleaned_word_token,hazm_lemmatized_word_token
0,"[تی, دی, جیکس, کشیش, نویسنده, سخنران, آمریکایی...","[تی, دی, جیکس, کشیش, نویسنده, سخنران, آمریکایی..."
1,"[کتاب, حاضر, اینک, دسترس, خوانندگان, محترم, قر...","[کتاب, حاضر, اینک, دسترس, خوانندگان, محترم, قر..."
2,"[دکتر, فتح, الله, بینا, تحصیلات, رشته, پزشکی, ...","[دکتر, فتح, الله, بینا, تحصیلات, رشته, پزشک, د..."
3,"[مجموعه, مطالبیست, گروه, Evolution, توسط, اینج...","[مجموعه, مطالبیست, گروه, Evolution, توسط, اینج..."
4,"[کتاب, آسمان, پرستاره, نوشته‌ی, کتی, هایدن, زب...","[کتاب, آسمان, پرستاره, نوشته, کت, هایدن, زبان,..."

In [17]:
# printing the first 5 rows of the persian df and word_token and hazm_stemmed_word_token columns
for index, row in df_persian.iterrows():
    for word, stemmed, lemmatized in zip(row["hazm_cleaned_word_token"], row["hazm_stemmed_word_token"], row["hazm_lemmatized_word_token"]):
        print(word, stemmed, lemmatized)
    break

تی ت تی
دی د دی
جیکس جیکس جیکس
کشیش کش کشیش
نویسنده نویسنده نویسنده
سخنران سخنر سخنران
آمریکایی آمریکا آمریکایی
سمینار‌های سمینار سمینار‌های
تی ت تی
دی د دی
جیکس جیکس جیکس
انگیزشی انگیزش انگیزش
مذهبی مذهب مذهب
دلیل دلیل دلیل
ایران ایر ایران
سخنران سخنر سخنران
انگیزشی انگیزش انگیزش
سیاه سیاه سیاه
پوست پوس پوست
لقب لقب لقب
زندگینامه زندگینامه زندگینامه
تی ت تی
دی د دی
جیکس جیکس جیکس
شاهد شاهد شاهد
فعالیت‌های فعالیت فعالیت
مختلفی مختلف مختلف
خواهان خواه خواهان
تجربه تجربه تجربه
تلاش تلا تلاش
مواردی موارد موارد
اعلام اعلا اعلام
فعالیت‌های فعالیت فعالیت
جیکس جیکس جیکس
کشیش کش کشیش
خانه خانه خانه
پاتر پا پاتر
مخاطبان مخاطب مخاطب
موعظه‌های موعظه موعظه
سخنرانی‌ها سخنرانی سخنرانی‌ها
تی ت تی
دی د دی
جیکس جیکس جیکس
کلیسا کلیسا کلیسا
شبکه‌های شبکه شبکه
تلویزیونی تلویزیون تلویزیون
رادیویی رادیو رادیو
مختلف مختلف مختلف
کتاب کتاب کتاب
گزیده‌ای گزیده گزیده
سخنرانی‌های سخنرانی سخنرانی‌های
جیکز جیکز جیکز
سخنران‌های سخنران سخنران
انگیزشی انگیزش انگیزش
دنیا دنیا دنیا
امید امید امید
مطالعه مطالعه مطالعه
دقیق دقیق دقیق
باور باور باور
عمیق عمیق عمیق
تغییری تغییر تغییر
مثبت مثب مثبت
زندگیتان زندگ زندگیتان
ایجاد ایجاد ایجاد

In [19]:
# serialize persian df using pickle
import pickle

with open('persian_df.pickle', 'wb') as handle:
    pickle.dump(df_persian, handle, protocol=pickle.HIGHEST_PROTOCOL)

# deserialize persian df using pickle
with open('persian_df.pickle', 'rb') as handle:
    df_persian = pickle.load(handle)

df_persian.head()

,title,date,content,category,author,comments,sent_token,word_token,hazm_cleaned_word_token,hazm_stemmed_word_token,hazm_lemmatized_word_token
0,بهترین درسهای زندگی‎,۲ دی ۱۳۹۸,تی دی جیکس یک کشیش، نویسنده، سخنران آمریکایی ...,روانشناسی,سارا رزولت,بدون دیدگاه,[تی دی جیکس یک کشیش نویسنده سخنران آمریکایی اس...,"[تی, دی, جیکس, یک, کشیش, نویسنده, سخنران, آمری...","[تی, دی, جیکس, کشیش, نویسنده, سخنران, آمریکایی...","[ت, د, جیکس, کش, نویسنده, سخنر, آمریکا, سمینار...","[تی, دی, جیکس, کشیش, نویسنده, سخنران, آمریکایی..."
1,از سلاجقه تا صفویه,۱ دی ۱۳۹۸,کتاب حاضر که اینک در دسترس خوانندگان محترم قر...,تاریخ ایران,نصرت الله مشکوتی,بدون دیدگاه,[کتاب حاضر که اینک در دسترس خوانندگان محترم قر...,"[کتاب, حاضر, که, اینک, در, دسترس, خوانندگان, م...","[کتاب, حاضر, اینک, دسترس, خوانندگان, محترم, قر...","[کتاب, حاضر, اینک, دسترس, خوانندگ, محتر, قرار,...","[کتاب, حاضر, اینک, دسترس, خوانندگان, محترم, قر..."
2,سرگذشت رضاشاه,۲۹ آذر ۱۳۹۸,دکتر فتح الله بینا تحصیلات خود را در رشته پزش...,تاریخ ایران,فتح الله بینا,بدون دیدگاه,[دکتر فتح الله بینا تحصیلات خود را در رشته پزش...,"[دکتر, فتح, الله, بینا, تحصیلات, خود, را, در, ...","[دکتر, فتح, الله, بینا, تحصیلات, رشته, پزشکی, ...","[دک, فتح, الله, بینا, تحصیل, رشته, پزشک, دنبال...","[دکتر, فتح, الله, بینا, تحصیلات, رشته, پزشک, د..."
3,سیری نوین در فرگشت و اسرار مغز,۲۸ آذر ۱۳۹۸,مجموعه پیش رو مطالبیست که در گروه Evolution ت...,علم و دانش,مانی منوچهری,بدون دیدگاه,[مجموعه پیش رو مطالبیست که در گروه Evolution ت...,"[مجموعه, پیش, رو, مطالبیست, که, در, گروه, Evol...","[مجموعه, مطالبیست, گروه, Evolution, توسط, اینج...","[مجموعه, مطالبیس, گروه, Evolution, توسط, اینجا...","[مجموعه, مطالبیست, گروه, Evolution, توسط, اینج..."
4,آسمان پرستاره,۲۶ آذر ۱۳۹۸,کتاب آسمان پرستاره نوشته‌ی کتی هایدن، به زبان...,کودکان و نوجوانان,کتی هایدن,بدون دیدگاه,[کتاب آسمان پرستاره نوشته‌ی کتی هایدن به زبانی...,"[کتاب, آسمان, پرستاره, نوشته‌ی, کتی, هایدن, به...","[کتاب, آسمان, پرستاره, نوشته‌ی, کتی, هایدن, زب...","[کتاب, آس, پرستاره, نوشته, کت, هایدن, زبان, سا...","[کتاب, آسمان, پرستاره, نوشته, کت, هایدن, زبان,..."

In [20]:
# now we create postings
all_tokens_dict = {}

# first we iterate over each row
for index, row in df_persian.iterrows():
    cleaned_word_tokens = row["hazm_cleaned_word_token"]
    content = row["content"]
    #we count occurences of each word in the cleaned_word_tokens
    cleaned_word_tokens_set = set(cleaned_word_tokens)
    for token in cleaned_word_tokens_set:
        count = cleaned_word_tokens.count(token)
        # if the token is not in the dict, then we add it
        if token not in all_tokens_dict:
            all_tokens_dict[token] = []
        # we add the index of the row and the count of the token in the row to the dict
        all_tokens_dict[token].append((index, count))

In [25]:
# sort the lists in each entry of the dict based on the count of the token
for token in all_tokens_dict:
    all_tokens_dict[token].sort(key=lambda x: x[1], reverse=True)

# print the first 5 entries of the dict
for token in list(all_tokens_dict.keys())[:5]:
    print(all_tokens_dict[token])

print(all_tokens_dict['کشیش'])

[(0, 1), (854, 1), (1156, 1), (2026, 1), (2276, 1)]
[(429, 10), (2105, 3), (0, 1), (9, 1), (31, 1), (256, 1), (266, 1), (380, 1), (408, 1), (487, 1), (488, 1), (648, 1), (791, 1), (949, 1), (991, 1), (999, 1), (1123, 1), (1150, 1), (1166, 1), (1168, 1), (1194, 1), (1236, 1), (1287, 1), (1296, 1), (1316, 1), (1344, 1), (1387, 1), (1505, 1), (1539, 1), (1648, 1), (1649, 1), (1684, 1), (1715, 1), (1900, 1), (2037, 1), (2056, 1), (2276, 1)]
[(0, 1), (336, 1), (933, 1), (1092, 1), (1419, 1), (1833, 1), (2045, 1), (2135, 1), (2401, 1)]
[(0, 1), (1133, 1), (1138, 1), (1419, 1), (1439, 1)]
[(73, 6), (609, 4), (2007, 4), (205, 3), (1355, 3), (1701, 3), (40, 2), (264, 2), (541, 2), (574, 2), (957, 2), (984, 2), (1095, 2), (1123, 2), (1236, 2), (1965, 2), (1985, 2), (1990, 2), (2156, 2), (2437, 2), (0, 1), (8, 1), (66, 1), (67, 1), (94, 1), (97, 1), (136, 1), (187, 1), (202, 1), (221, 1), (254, 1), (265, 1), (291, 1), (303, 1), (318, 1), (332, 1), (362, 1), (390, 1), (415, 1), (427, 1), (456, 1), (474, 1), (484, 1), (492, 1), (505, 1), (506, 1), (525, 1), (559, 1), (563, 1), (565, 1), (581, 1), (596, 1), (598, 1), (617, 1), (682, 1), (687, 1), (706, 1), (743, 1), (751, 1), (762, 1), (893, 1), (903, 1), (939, 1), (952, 1), (991, 1), (1011, 1), (1020, 1), (1044, 1), (1059, 1), (1086, 1), (1087, 1), (1098, 1), (1129, 1), (1153, 1), (1163, 1), (1174, 1), (1187, 1), (1222, 1), (1266, 1), (1279, 1), (1284, 1), (1329, 1), (1337, 1), (1344, 1), (1346, 1), (1362, 1), (1365, 1), (1371, 1), (1374, 1), (1376, 1), (1395, 1), (1401, 1), (1423, 1), (1464, 1), (1474, 1), (1494, 1), (1515, 1), (1557, 1), (1583, 1), (1593, 1), (1615, 1), (1622, 1), (1626, 1), (1640, 1), (1648, 1), (1664, 1), (1665, 1), (1674, 1), (1685, 1), (1697, 1), (1700, 1), (1776, 1), (1781, 1), (1785, 1), (1799, 1), (1834, 1), (1839, 1), (1879, 1), (1904, 1), (1934, 1), (1958, 1), (1966, 1), (1995, 1), (2037, 1), (2041, 1), (2118, 1), (2172, 1), (2201, 1), (2323, 1), (2385, 1)]
[(1156, 4), (0, 2), (1509, 2), (937, 1), (1272, 1)]

In [ ]:
# Now we analyze the time complexity of what we just did
# We are iterating over each row in our df,
# So if we call the count of rows, R, then the time complexity is O(R * f())
# where f() is the time complexity of the code inside the loop
# we are using set() to remove duplicates from the cleaned_word_tokens
# so the time complexity of set() is O(n)
# we are using count() to count the occurences of each token in the cleaned_word_tokens
# so the time complexity of count() is O(n)
# So the time complexity of the code inside the loop is O(n + n) = O(2n) = O(n)
# So the time complexity of what we just did is O(R * n)

# finally we sort each entry of the dict based on the count of the token
# so the time complexity of the sort is O(n log n)
# So if we have T entries in the dict, then the time complexity of the sort is O(T * n log n)

# So the time complexity of what we just did is O(R * n + T * n log n)
# Since T >>> R, we can ignore R and say that the time complexity of what we just did is O(T * n log n)

In [26]:
# we convert the dict to a df and then to a csv file
import pandas as pd

df_postings = pd.DataFrame.from_dict(all_tokens_dict, orient='index')
df_postings.to_csv('postings.csv')
df_postings.head()

,0,1,2,3,4,5,6,7,8,9,...,1335,1336,1337,1338,1339,1340,1341,1342,1343,1344
کلیسا,"(0, 1)","(854, 1)","(1156, 1)","(2026, 1)","(2276, 1)",None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
آمریکایی,"(429, 10)","(2105, 3)","(0, 1)","(9, 1)","(31, 1)","(256, 1)","(266, 1)","(380, 1)","(408, 1)","(487, 1)",...,None,None,None,None,None,None,None,None,None,None
گزیده‌ای,"(0, 1)","(336, 1)","(933, 1)","(1092, 1)","(1419, 1)","(1833, 1)","(2045, 1)","(2135, 1)","(2401, 1)",None,...,None,None,None,None,None,None,None,None,None,None
سخنرانی‌ها,"(0, 1)","(1133, 1)","(1138, 1)","(1419, 1)","(1439, 1)",None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
دنیا,"(73, 6)","(609, 4)","(2007, 4)","(205, 3)","(1355, 3)","(1701, 3)","(40, 2)","(264, 2)","(541, 2)","(574, 2)",...,None,None,None,None,None,None,None,None,None,None